/** Shared empty platformStats/summary payload for Admin reset scripts. */

export const PLATFORM_STATS_RESET_BASE = {
  totalSignUps: 0,
  totalStudySeconds: 0,
  totalQuizAttempts: 0,
  dailyActiveUsers: 0,
  weeklyActiveUsers: 0,
  returningUsers: 0,
  averageSessionDurationSeconds: 0,
  totalSessions: 0,
  sessionsPerUserAverage: 0,
  dropOffAfterFirstSession: 0,
  studySecondsBySubject: { math: 0, addMath: 0, physics: 0 },
  studySecondsByHourOfDay: Object.fromEntries([...Array(24)].map((_, h) => [String(h), 0])),
  studySecondsByDayOfWeek: { mon: 0, tue: 0, wed: 0, thu: 0, fri: 0, sat: 0, sun: 0 },
  averageStudySessionLengthSeconds: 0,
  peakStudyHour: 0,
  peakStudyDay: '',
  topicViewCounts: {},
  topicCompletionCounts: {},
  topicCompletionRates: {},
  mostRevisitedTopics: [],
  notesReadCounts: {},
  chapterCompletionCounts: {},
  subjectEngagementRatio: { math: 0, addMath: 0, physics: 0 },
  quizAttemptsBySubject: { math: 0, addMath: 0, physics: 0 },
  quizAverageScoreBySubject: { math: 0, addMath: 0, physics: 0 },
  quizPassRateBySubject: { math: 0, addMath: 0, physics: 0 },
  quizAverageScoreByTopic: {},
  quizRetakeRate: 0,
  quizScoreDistribution: { '0-20': 0, '21-40': 0, '41-60': 0, '61-80': 0, '81-100': 0 },
  firstAttemptPassRate: 0,
  averageAttemptsBeforePass: 0,
  totalXpAwarded: 0,
  xpBySource: { quiz: 0, notes: 0, streak: 0, chapter: 0 },
  averageXpPerUser: 0,
  streakDistribution: { '1-3': 0, '4-7': 0, '8-14': 0, '15+': 0 },
  usersWithActiveStreak: 0,
  averageStreakLength: 0,
  leaderboardParticipationRate: 0,
  day1RetentionRate: 0,
  day7RetentionRate: 0,
  day30RetentionRate: 0,
  averageDaysBetweenSessions: 0,
  churnedUsers: 0,
  reactivatedUsers: 0,
  signUpsByDay: {},
  signUpsByReferralSource: { discord: 0, direct: 0, other: 0 },
}
